# Generated by Django 2.1.3 on 2019-01-05 09:42

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0008_auto_20181225_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupuser',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='cupuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='cupuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='姓氏'),
        ),
        migrations.AlterField(
            model_name='cupuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='cupuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='e.g. 0912345678', max_length=10, null=True, verbose_name='電話號碼'),
        ),
        migrations.AlterField(
            model_name='cupuser',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='公司稱號'),
        ),
        migrations.AlterField(
            model_name='cupuser',
            name='username',
            field=models.CharField(error_messages={'unique': '有人使用這個名字了'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用戶名'),
        ),
    ]
